// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package login

import (
	"root/models"

	mock "github.com/stretchr/testify/mock"
)

// newMockrepository creates a new instance of mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockrepository {
	mock := &mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockrepository is an autogenerated mock type for the repository type
type mockrepository struct {
	mock.Mock
}

type mockrepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockrepository) EXPECT() *mockrepository_Expecter {
	return &mockrepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type mockrepository
func (_mock *mockrepository) CreateUser(user *models.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockrepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user *models.User
func (_e *mockrepository_Expecter) CreateUser(user interface{}) *mockrepository_CreateUser_Call {
	return &mockrepository_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *mockrepository_CreateUser_Call) Run(run func(user *models.User)) *mockrepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.User
		if args[0] != nil {
			arg0 = args[0].(*models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockrepository_CreateUser_Call) Return(err error) *mockrepository_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepository_CreateUser_Call) RunAndReturn(run func(user *models.User) error) *mockrepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByName provides a mock function for the type mockrepository
func (_mock *mockrepository) GetUserByName(u *models.User) error {
	ret := _mock.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = returnFunc(u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepository_GetUserByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByName'
type mockrepository_GetUserByName_Call struct {
	*mock.Call
}

// GetUserByName is a helper method to define mock.On call
//   - u *models.User
func (_e *mockrepository_Expecter) GetUserByName(u interface{}) *mockrepository_GetUserByName_Call {
	return &mockrepository_GetUserByName_Call{Call: _e.mock.On("GetUserByName", u)}
}

func (_c *mockrepository_GetUserByName_Call) Run(run func(u *models.User)) *mockrepository_GetUserByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.User
		if args[0] != nil {
			arg0 = args[0].(*models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockrepository_GetUserByName_Call) Return(err error) *mockrepository_GetUserByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepository_GetUserByName_Call) RunAndReturn(run func(u *models.User) error) *mockrepository_GetUserByName_Call {
	_c.Call.Return(run)
	return _c
}
